name: Build ALParserCLI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish CLI as self-contained exe
      run: dotnet publish ./ALParserCLI/ALParserCLI.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o output

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: ALParserCLI
        path: output/ALParserCLI.exe
