name: Build ALParserCLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ALParserCLI/ALParserCLI.csproj

      - name: Build ALParserCLI
        run: dotnet build ALParserCLI/ALParserCLI.csproj --configuration Release --no-restore

      - name: Publish ALParserCLI (self-contained single file)
        run: |
          dotnet publish ALParserCLI/ALParserCLI.csproj \
            --configuration Release \
            --runtime win-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o ./output

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: ALParserCLI-win-x64
          path: ./output/*
